# fly.toml app configuration file generated for wjw-e675pw on 2026-08-26T16:08:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'warga-jaga-warga-wjw'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
